<?php
require_once "auth.php";
require_once "../config/config.php";
require_once "../vendor/autoload.php";

use Dompdf\Dompdf;

$table = "reports";

// ===== AUTO DETECT kolom ID =====
$possibleIdCols = ["id", "report_id", "id_report"];
$idCol = null;
foreach($possibleIdCols as $col){
  $c = $conn->query("SHOW COLUMNS FROM $table LIKE '$col'");
  if($c && $c->num_rows > 0){
    $idCol = $col;
    break;
  }
}

// ===== AUTO DETECT kolom TANGGAL =====
$possibleDateCols = ["report_date","created_at","tanggal","date"];
$dateCol = null;
foreach($possibleDateCols as $col){
  $c = $conn->query("SHOW COLUMNS FROM $table LIKE '$col'");
  if($c && $c->num_rows > 0){
    $dateCol = $col;
    break;
  }
}

// ==== ambil data dari DB kalau tabel ada ====
$rows = [];
$check = $conn->query("SHOW TABLES LIKE '$table'");

if ($check && $check->num_rows > 0) {

    // pilih ORDER BY terbaik
    if($dateCol){
      $sql = "SELECT * FROM $table ORDER BY $dateCol DESC";
    } elseif($idCol){
      $sql = "SELECT * FROM $table ORDER BY $idCol DESC";
    } else {
      $sql = "SELECT * FROM $table";
    }

    $res = $conn->query($sql);
    while ($r = $res->fetch_assoc()) {
        $rows[] = $r;
    }

} else {
    // ==== fallback dummy kalau tabel belum ada ====
    $rows = [
        ["id"=>1,"type"=>"lost","title"=>"Tas Ransel Biru","category"=>"Aksesoris","location"=>"Area Kantin","status"=>"pending"],
        ["id"=>2,"type"=>"found","title"=>"Sepeda Lipat","category"=>"Kendaraan","location"=>"Pos Satpam","status"=>"approved"],
        ["id"=>3,"type"=>"lost","title"=>"Kartu Mahasiswa","category"=>"Dokumen","location"=>"Perpustakaan","status"=>"rejected"],
    ];
}

// ==== helper biar aman kalau kolom beda nama ====
function col($row, $possible, $default="-") {
    foreach($possible as $p){
        if(isset($row[$p])) return $row[$p];
    }
    return $default;
}

// ==== bikin HTML PDF ====
$html = '
<style>
  body { font-family: Arial, sans-serif; font-size: 12px; }
  h2 { text-align:center; margin-bottom:5px; }
  .meta { text-align:center; font-size:11px; margin-bottom:15px; color:#555; }
  table { width:100%; border-collapse: collapse; }
  th, td { border:1px solid #999; padding:6px; }
  th { background:#f2f2f2; }
</style>

<h2>Laporan Lost & Found Campus</h2>
<div class="meta">Generated by Admin Panel | '.date("Y-m-d H:i").'</div>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Type</th>
      <th>Barang</th>
      <th>Kategori</th>
      <th>Lokasi</th>
      <th>Tanggal</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
';

foreach($rows as $row){
    $id     = col($row, ["id","report_id","id_report"]);
    $type   = strtoupper(col($row, ["type","report_type"]));
    $title  = col($row, ["title","item_name","barang"]);
    $cat    = col($row, ["category","kategori"]);
    $loc    = col($row, ["location","lokasi"]);
    $date   = col($row, ["report_date","created_at","date","tanggal"]);
    $status = col($row, ["status"]);

    $html .= "
    <tr>
      <td>$id</td>
      <td>$type</td>
      <td>$title</td>
      <td>$cat</td>
      <td>$loc</td>
      <td>$date</td>
      <td>$status</td>
    </tr>
    ";
}

$html .= '
  </tbody>
</table>
';

// ==== render PDF ====
$dompdf = new Dompdf();
$dompdf->loadHtml($html);
$dompdf->setPaper("A4", "landscape");
$dompdf->render();
$dompdf->stream("lostfound_report.pdf", ["Attachment" => true]);
exit;
